{
    'name': "HMS App",
    'summary': """ """,
    'author': "Yusuf Abu Alam",
    'category': 'Productivity',
    'version': '17.0.0.1.0',
    'depends': ['base',
                'crm',
                ],
    'application': True,
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/base_menus.xml',
        'views/patient.xml',
        'views/department.xml',
        'views/doctor.xml',
        'views/res_partner.xml',
        'wizard/add_log_wizard.xml',
        'reports/patient_print.xml',
    ],
}